Femgineer logo
WriteSpeakCode/2017.writespeakcode.com pull request #49
Opened 2017-04-13 17:15 UTC by dalrayes

Adds bronze sponsor section
Adds Femgineer logo and description
Moves sponsorship blurb to bronze section
@jarmstrng

2017-04-15 14:17 UTC, jarmstrng commented
can you add a `.gitignore` file and add `.DS_Store` to it, so that those two files aren't committed?

2017-04-15 14:24 UTC, jarmstrng requested changes
it looks like you missed the changes to the trello card :upside_down_face: the logo needs to be in a section titled Childcare, not Bronze, and they don't get text

2017-04-15 14:25 UTC, jarmstrng commented on index.html
>  			<div class="col-md-4">
Can we get the sponsor-us blurb with a `col-md-8` instead of 4, so that it fills the rest of the container?

2017-04-16 14:54 UTC, dalrayes commented
@jarmstrng Added gitignore, updated to childcare sponsor and widened the 'sponsor us' box.

2017-04-17 10:58 UTC, jarmstrng commented
Hm, it looks like the .DS_Store files are still in the commit, can you remove them?

2017-04-17 11:00 UTC, jarmstrng commented on index.html
> +				</div>
Please remove this text, their sponsor level does not include it

2017-04-20 17:01 UTC, dalrayes commented
@jarmstrng Deletes DS Store and sponsor description

2017-04-22 16:45 UTC, jarmstrng approved these changes

2017-04-22 16:45 UTC, merged