updated copy
WriteSpeakCode/2017.writespeakcode.com pull request #79
Opened 2017-05-27 18:32 UTC by laumontemayor

2017-05-27 18:41 UTC, laumontemayor commented
https://trello.com/c/RFBPQnGS/126-tweaks-from-lateesha

2017-05-27 18:41 UTC, Euraldius commented
💃

2017-05-30 22:15 UTC, jarmstrng requested changes

2017-05-30 22:15 UTC, jarmstrng commented on index.html
> +				<p class="qcTabDesc">Sponsorship is the most effective way to recruit talented, driven women to fill key technical positions and demonstrate your commitment to the professional development of wom
Ooh, looks like we're missing a `>` on the break - the link doesn't work

2017-05-30 22:16 UTC, jarmstrng commented on index.html
> +				<p class="qcTabDesc">Sponsorship is the most effective way to recruit talented, driven women to fill key technical positions and demonstrate your commitment to the professional development of wom
I think that comment pinged you but just in case: @laumontemayor

2017-05-31 15:06 UTC, laumontemayor commented
@jarmstrng checked and looks good on staging on Safari | Chrome | IE | Firefox | Brave 💃

2017-05-31 21:44 UTC, jarmstrng approved these changes

2017-05-31 21:45 UTC, jarmstrng commented
@laumontemayor Looks good! Please merge into master & deploy master to prod, let me know if you have any issues (though I'll be on a boat tonight, so if prod breaks just roll it back 😂 )

2017-06-08 22:44 UTC, merged